### PR TITLE
🤖 Update URL in tests

### PR DESCRIPTION
**Pull request by arybolovlev**
### Description

Update the URL in tests to `https://www.hashicorp.com` since `https://example.com` started returning 405 error code.

#### Tests

- [E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:fix-tests)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=fix-tests&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:fix-tests)
- [E2E on Terraform Enterprise](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfe.yaml?query=branch:fix-tests)
- [![E2E on Terraform Enterprise [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfe.yaml/badge.svg?branch=fix-tests&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfe.yaml?query=branch:fix-tests)

### Usage Example

N/A.

### References

N/A.

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### CODE REVIEW

**Review by SarahFrench — DISMISSED** [review]
We had a similar issue in the Google provider due to example.com changing behaviour 😆

Does this test also expect 404s?

**Comment by SarahFrench** [comment]
(approving in a LGTM way)

**Comment by arybolovlev** [comment]
> Approved in a LGTM way but just saw the test failures - removed approval

Yeah, I forgot to update some other tests. Done, re-run tests.

**Comment by arybolovlev** [comment]
> We had a similar issue in the Google provider due to example.com changing behaviour 😆
> 
> Does this test also expect 404s?

In this case, it is expected to be one of 200 family.

**Review by SarahFrench — APPROVED** [review]

**Pull request merged**
