### PR TITLE
🚀 Add workspace trigger patterns to CRD

### PR DESCRIPTION
**Pull request by baptman21**
### Description

Add the fields `FileTriggersEnabled`, `TriggerPatterns` and `TriggerPrefixes` to the Workspace CRD to allow the user to manage those fields.

The fields are already present in the `go-tfe` package but are currently not editable from the CRD.

### Usage Example

* Deploy a workspace with the configuration
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: tmp
spec:
  allowDestroyPlan: false
  applyMethod: auto
  description: "Example with Trigger Patterns"
  executionMode: agent
  name: example
  organization: padoa
  project:
    name: Default Project
  tags:
  - test
  terraformVariables:
    - hcl: false
      name: env
      sensitive: false
      value: dev
  token:
    secretKeyRef:
      key: token
      name: example-token
  versionControl:
    branch: main
    oAuthTokenID: ot-XXXXXXXXXXX
    repository: example
  triggerPatterns:
    - "example/test/*"
  fileTriggersEnabled: true
  workingDirectory: example/test
```

### References

- Fixes [GH-0314](https://github.com/hashicorp/terraform-cloud-operator/issues/314)

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### CODE REVIEW

**Comment by arybolovlev** [comment]
Hi @baptman21,

Thank you for your interest in contributing to this project. I am going to review this PR next week and come back to you with my comments.

Thank you.

**Comment by arybolovlev** [comment]
Hi @baptman21,

Thank you again for your interest in contributing to this project.

There are a few things that we need to work on here and  I would be happy to assist you with them. Please let me know if you prefer to get a full list or we can go step by step.

To set the right expectation, we won't be able to include your changes in the nearest release since it will happen soon and we have already settled with the list of the changes that will be included in it.

We can start with Workspace CR [validation](https://github.com/hashicorp/terraform-cloud-operator/blob/main/api/v1alpha2/workspace_validation.go). It aims to catch possible mistakes in the custom resources. Here are two that we can begin with:
- Only one of `TriggerPatterns` or `TriggerPrefixes` is allowed since they would conflict with each other.
- `TriggerPrefixes` requires non-empty `WorkingDirectory`.

Please, update [unit tests](https://github.com/hashicorp/terraform-cloud-operator/blob/main/api/v1alpha2/workspace_validation_test.go) for validations that you will add. You should be able to run them without accessing TFC. [Here](https://github.com/hashicorp/terraform-cloud-operator/blob/main/CONTRIBUTING.md#test-changes) you can read how to do that.

Please, let me know if you need assistance.

Thanks!

**Comment by baptman21** [comment]
Thanks for the update. I wasn't sure whether we needed to check here the validity of the settings or let the TF cloud API throw the error.  I will make the changes as you requested.

**Comment by baptman21** [comment]
Hello @arybolovlev,

I added the validation for those 3 cases:
* Only one of `TriggerPatterns` or `TriggerPrefixes` can be defined
* `TriggerPrefixes` required non-empty `WorkingDirectory`
* `TriggerPatterns` or `TriggerPrefixes` require `FileTriggerEnabled` set to true

The last one is not a specification of the API but rather a way to avoid mistakes like forgetting to enable the `FileTriggerEnabled` but defining the patterns, what do you think ?

Let me know if there are any other changes to make.

**Pull request closed without merging**
